/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    IEpCalendar: typeof import('~icons/ep/calendar')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpUnlock: typeof import('~icons/ep/unlock')['default']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
